import type { UnitDefinition, UnitTypeId } from '../core/types';
import { UNIT_HP_MAX } from '../core/constants';

// Central registry of every unit type. Balancing values live here; nothing in
// the game should hard-code stats anywhere else.

export const UNIT_TYPES: Record<UnitTypeId, UnitDefinition> = {
  // --- LAND ---
  infantry: {
    id: 'infantry',
    name: 'Infanterie',
    domain: 'land',
    movement: 2,
    attack: 3,
    defense: 4,
    sight: 3,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 2,
    canCaptureCities: true,
    symbol: 'I',
  },
  special: {
    id: 'special',
    name: 'Spezialkräfte',
    domain: 'land',
    movement: 3,
    attack: 5,
    defense: 5,
    sight: 4,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 4,
    canCaptureCities: true,
    symbol: 'S',
  },
  tank: {
    id: 'tank',
    name: 'Panzer',
    domain: 'land',
    movement: 4,
    attack: 7,
    defense: 5,
    sight: 3,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 5,
    canCaptureCities: true,
    symbol: 'T',
  },
  flak: {
    id: 'flak',
    name: 'Flak/Radar',
    domain: 'land',
    movement: 1,
    attack: 2,
    defense: 6,
    sight: 6,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 4,
    canCaptureCities: false,
    symbol: 'F',
    notes: 'Bonus gegen Lufteinheiten',
    bonusVs: { air: 2.0 },
  },

  // --- AIR ---
  fighter: {
    id: 'fighter',
    name: 'Jäger',
    domain: 'air',
    movement: 7,
    attack: 5,
    defense: 4,
    sight: 6,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 5,
    canCaptureCities: false,
    symbol: 'J',
    notes: 'Stark gegen Bomber',
    bonusVs: { air: 1.6 },
  },
  divebomber: {
    id: 'divebomber',
    name: 'Sturzkampfflugzeug',
    domain: 'air',
    movement: 6,
    attack: 7,
    defense: 2,
    sight: 5,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 5,
    canCaptureCities: false,
    symbol: 'B',
    notes: 'Stark gegen Panzer/Städte',
    bonusVs: { land: 1.4 },
  },
  transport: {
    id: 'transport',
    name: 'Transportflugzeug',
    domain: 'air',
    movement: 6,
    attack: 0,
    defense: 2,
    sight: 4,
    range: 0,
    hpMax: UNIT_HP_MAX,
    productionTurns: 5,
    canCaptureCities: false,
    symbol: 'C',
    notes: 'Transportlogik folgt',
  },

  // --- SEA ---
  destroyer: {
    id: 'destroyer',
    name: 'Zerstörer',
    domain: 'sea',
    movement: 5,
    attack: 5,
    defense: 4,
    sight: 5,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 6,
    canCaptureCities: false,
    symbol: 'D',
    notes: 'Kann U-Boote entdecken',
    bonusVs: { subsea: 1.8 },
  },
  submarine: {
    id: 'submarine',
    name: 'U-Boot',
    domain: 'subsea',
    movement: 4,
    attack: 7,
    defense: 3,
    sight: 4,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 6,
    canCaptureCities: false,
    symbol: 'U',
    notes: 'Schwer zu entdecken',
  },
  carrier: {
    id: 'carrier',
    name: 'Flugzeugträger',
    domain: 'sea',
    movement: 4,
    attack: 2,
    defense: 7,
    sight: 5,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 10,
    canCaptureCities: false,
    symbol: 'A',
    notes: 'Carrier-System folgt',
  },
  battleship: {
    id: 'battleship',
    name: 'Schlachtschiff',
    domain: 'sea',
    movement: 4,
    attack: 8,
    defense: 7,
    sight: 5,
    range: 1,
    hpMax: UNIT_HP_MAX,
    productionTurns: 9,
    canCaptureCities: false,
    symbol: 'X',
  },
};

export const ALL_UNIT_TYPE_IDS: UnitTypeId[] = Object.keys(UNIT_TYPES) as UnitTypeId[];
